Always use node id and node name in messages.
citusdata/pg_auto_failover pull request #462
Opened 2020-10-15 15:14 UTC by DimCitus

Normalize the use of the notation "node %d \"%s\" (%s:%d)" in every message
that shows a node to the user. That helps a lot with debugging, and also,
when people name things, they usually like using the name again.

2020-10-16 11:33 UTC, JelteF requested changes

2020-10-16 11:33 UTC, JelteF commented on src/bin/pg_autoctl/fsm_transition.c
> +				  "node %d \"%s\" at %s:%d, see above for details",
```suggestion
				  "node %d \"%s\" at (%s:%d), see above for details",
```

2020-10-16 11:33 UTC, JelteF commented on src/monitor/formation_metadata.c
> +						primaryNode->nodeName,
NODE_FORMAT_ARGS

2020-10-16 11:33 UTC, JelteF commented on src/monitor/formation_metadata.c
> +		primaryNode->nodeId,
NODE_FORMAT_ARGS

2020-10-16 11:33 UTC, JelteF commented on src/monitor/node_active_protocol.c
> +							"%d \"%s\" (%s:%d)",
```suggestion
							NODE_FORMAT,
```

2020-10-16 13:51 UTC, DimCitus commented on src/bin/pg_autoctl/fsm_transition.c
> +				  "node %d \"%s\" at %s:%d, see above for details",
Fixed without the extra "at".

2020-10-16 13:51 UTC, DimCitus commented on src/monitor/formation_metadata.c
> +		primaryNode->nodeId,
Done.

2020-10-16 13:51 UTC, DimCitus commented on src/monitor/node_active_protocol.c
> +							"%d \"%s\" (%s:%d)",
Done.

2020-10-26 12:30 UTC, DimCitus commented
I think this PR is ready for a last round of review @JelteF !

2020-10-26 12:52 UTC, JelteF approved these changes
LGTM, I left some small suggestions (formatting, missed macro usage and typos in existing log messages)

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
> +			"after " NODE_FORMAT
```suggestion
			" to stop_replication after " NODE_FORMAT
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
> +					"are healthy anymore.",
nit: leading space for consistency sake

```suggestion
					" to wait_primary now that none of the standbys"
					" are healthy anymore.",
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
> +			"activeNode is %d \"%s\" (%s:%d) and reported state \"%s\"",
```suggestion
			"activeNode is " NODE_FORMAT
			" and reported state \"%s\"",
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
> +				"activeNode is %d \"%s\" (%s:%d) and reported state \"%s\"",
```suggestion
				"activeNode is " NODE_FORMAT
				" and reported state \"%s\"",
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
> +				 node->nodeId, node->nodeName, node->nodeHost, node->nodePort);
```suggestion
				 NODE_FORMAT_ARGS(node));
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
> +				 node->nodeId, node->nodeName, node->nodeHost, node->nodePort);
```suggestion
				 NODE_FORMAT_ARGS(node));
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
> +				node->nodeId, node->nodeName, node->nodeHost, node->nodePort);
```suggestion
				NODE_FORMAT_ARGS(node));
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
>  			"One of the most advanced standby node in the group "
```suggestion
			"One of the most advanced standby nodes in the group "
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
> +				"The selected candidate %d \"%s\" (%s:%d) needs to fetch missing "
```suggestion
				"The selected candidate " NODE_FORMAT
				" needs to fetch missing "
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
>  				"and %d nodes reported their LSN position.",
```suggestion
				" became unhealthy and %d nodes reported their LSN position.",
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
>  				"and %d nodes reported their LSN position.",
```suggestion
				" became unhealthy and %d nodes reported their LSN position.",
```

2020-10-26 12:52 UTC, JelteF commented on src/monitor/group_state_machine.c
> +				" to fast_forward and %d nodes reported their LSN position.",
```suggestion
				" to fast_forward after %d nodes reported their LSN position.",
```

2020-10-26 13:28 UTC, merged