Register components manually
citusdata/pg_auto_failover pull request #474
Opened 2020-10-26 11:01 UTC by SaitTalhaNisanci

Component Governance detector cannot detect git components currently, so
we should register them manually for SDL.

Example result: https://msdata.visualstudio.com/Database%20Systems/_componentGovernance/citus-ha?_a=components&typeId=4985361&alerts-view-option=active

We also have `pg` and `subcommands`, as far as I remember now we kinda own `subcommands` and for `pg` we seem to take only two files, it seemed not necessary to add whole postgres repo for this.

2020-10-26 11:06 UTC, SaitTalhaNisanci commented on cgmanifest.json
> +            "DevelopmentDependency": true
This should probably be false

2020-10-27 09:09 UTC, JelteF commented on cgmanifest.json
> +            "DevelopmentDependency": true
yes, I agree

2020-10-30 14:36 UTC, SaitTalhaNisanci commented on cgmanifest.json
> +            "licenseDetail": [
For some reason, NOTICE generation doesn't automatically add this definition. But we can manually append this to the NOTICE file. It is probably okay for it to be not automated as we will generate the notice file only once.

2020-10-30 14:44 UTC, JelteF requested changes
Missing this dependency: https://github.com/mattiasgustavsson/libs

Which we use for parsing .ini files.

2020-11-18 14:17 UTC, JelteF approved these changes

2020-11-18 14:26 UTC, merged

2020-11-18 14:35 UTC, DimCitus commented
Thanks team!