make NODES=3 NODES_ASYNC=2 NODES_PRIOS=50,0 NODES_SYNC_SB=0 cluster
citusdata/pg_auto_failover pull request #551
Opened 2020-12-14 11:53 UTC by DimCitus

This PR allows to setup an interactive testing/QA cluster with tmux with
full specifications of nodes replication settings. Before that the code was
conflating the replicationQuorum and the candidatePriority of nodes, and
that was limiting our testing abilities.

When unspecified, nodes are all created with --candidate-priority 0. Then it
is possible to specify one or more candidate priorities, which are used in
the order given. When more nodes are created than priorities are given, we
use the last specified priority again and again.

For instance --node-priorities 50,0 --nodes 3 results in using 50,0,0 as the
respective priorities for the nodes thus created.

2020-12-18 12:37 UTC, JelteF requested changes

2020-12-18 12:53 UTC, DimCitus commented on src/bin/pg_autoctl/cli_do_tmux.c
> +	while ((ptr = strchr(ptr, sep)) != NULL)
The `strtok` function is banned from the security audit.

2020-12-18 12:54 UTC, DimCitus commented on src/bin/pg_autoctl/cli_do_tmux.c
> +								   NodeStateToString(WAIT_PRIMARY_STATE));
Without this change we can't `make -j20 NODES=3 NODES_SYNC_SB=0 NODES_ASYNC=3 cluster` if I remember correctly... maybe we need to be smarter about what we want to wait for?

2021-01-11 15:02 UTC, DimCitus commented on src/bin/pg_autoctl/cli_do_tmux.c
> + * parseCandidatePriority parses the --node-priorities options on the command
Fixed, thanks.

2021-01-15 11:04 UTC, JelteF approved these changes

2021-01-15 11:28 UTC, merged